project: 
  type: website

website:
  title: "Ashley Bird - Data Science Portfolio"
  favicon: Images/favicon.png
  back-to-top-navigation: true
  site-url: https://bir20026.github.io/username.github.io.-/
  repo-url: https://github.com/bir20026/username.github.io.-
  issue-url: https://github.com/bir20026/username.github.io.-/issues
  repo-actions: [issue]

  page-footer: 
    border: true
    left: "Ashley Bird 2025 test test test"
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/ashleybird2026/

  navbar:
    background: primary
    search: true   
    right:
      - text: "Home"
        file: index.qmd
      - text: "DS250 Projects"
        file: 250_projects.qmd
      - text: "My Resume"
        file: resume.qmd

  sidebar:
    - title: "DS 250 Projects"
      style: "docked"
      background: light
      contents:
        - text: "DS250 Projects"
          file: 250_projects.qmd
        - text: "---"
        - text: "Project 3"
          file: 250_Projects/project3.qmd
        - text: "---"
        - text: "Project 4"
          file: 250_Projects/project4.qmd
        - text: "---"
        - text: "Project 5"
          file: 250_Projects/project5.qmd
        - text: "---"

format:  
  html:
    theme: #see this link to customize the theme with css (https://quarto.org/docs/output-formats/html-themes.html#dark-mode)
      light: flatly # more themes can be found [here](https://quarto.org/docs/output-formats/html-themes.html)
      dark: darkly
      #light: cosmo
      #dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true



